function [fitresult, gof] = createFit(pos_x, pos_y)
%CREATEFIT(POS_X,POS_Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : pos_x
%      Y Output: pos_y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Jul-2022 21:04:13


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( pos_x, pos_y );

% Set up fittype and options.
ft = fittype( 'gauss4' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0.62 0 0 0.65 0 0 0.68 0 0 0.71 0];
opts.StartPoint = [118 0.6295 0.00355114114105729 93.2066503189443 0.6235 0.00478573278068932 40.8033798606778 0.6385 0.00619169176517932 27.6425531687581 0.6175 0.0140319358008863];
opts.Upper = [Inf 0.65 Inf Inf 0.68 Inf Inf 0.71 Inf Inf 0.75 Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'pos_y vs. pos_x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel pos_x
ylabel pos_y
grid on


