function [fitresult, gof] = createFit(pos_x, pos_y)
%CREATEFIT(POS_X,POS_Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : pos_x
%      Y Output: pos_y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Aug-2022 02:17:32


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( pos_x, pos_y );

% Set up fittype and options.
ft = fittype( 'gauss4' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0.61 0 0 0.65 0 0 0.67 0 0 0.715 0];
opts.StartPoint = [222 0.7165 0.00286313742814472 165.251309692859 0.7225 0.00397873914609603 151.988536462422 0.7075 0.00387734277627835 92.1373403195326 0.7015 0.00596278862308495];
opts.Upper = [0 0.65 Inf Inf 0.67 Inf Inf 0.715 Inf Inf 0.76 Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'pos_y vs. pos_x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel pos_x
ylabel pos_y
grid on


